### ISSUE TITLE
Change gif

### ISSUE THREAD

**Issue by Darkkgreen** [giovana-morais/giovana-morais.github.io#1]
https://www.youtube.com/watch?v=YT9VDzs6B50

This would look so much better

**Comment by giovana-morais** [comment]
actually, i'm really close to change to this one: http://digitalspyuk.cdnds.net/16/21/640x320/landscape-1464342455-typing-cat-gif.gif

**Comment by giovana-morais** [comment]
this one is also cool

![Coragem](https://66.media.tumblr.com/1ac03edf7df988bb82fb926b2713516d/tumblr_mqirg6B6NT1qjwawyo1_500.gif)

**Comment by Darkkgreen** [comment]
Why not all of those

**Comment by giovana-morais** [comment]
nah, i'm into cleaner websites
